ALTER TABLE favorite MODIFY id BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE review MODIFY id BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE tag MODIFY id BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE users MODIFY id BIGINT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE review_tag MODIFY review_id BIGINT NOT NULL;
ALTER TABLE review_tag MODIFY tag_id BIGINT NOT NULL;
ALTER TABLE review_tag ADD PRIMARY KEY (review_id, tag_id);
